import * as Dialog from "@radix-ui/react-dialog";
import * as AvatarPrimitive from "@radix-ui/react-avatar";
import { X } from "lucide-react";
import { cn } from "@/lib/utils";
import type { User } from "@/types";
export function Button({ children, variant = "primary", size = "md", className, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "ghost" | "gold"; size?: "sm" | "md" | "lg" }) { return <button {...props} className={cn("inline-flex shrink-0 items-center justify-center gap-2 rounded-xl font-semibold transition-all duration-200 disabled:cursor-not-allowed disabled:opacity-50 active:scale-[.98]", size === "sm" ? "min-h-9 px-3 text-xs" : size === "lg" ? "min-h-12 px-6 text-sm" : "min-h-10 px-4 text-sm", variant === "primary" ? "bg-[#17468c] text-white hover:bg-[#0f3672] shadow-[0_4px_12px_#17468c20]" : variant === "secondary" ? "border border-[#dce5ef] bg-white text-[#17468c] hover:bg-[#f5f8fc]" : variant === "gold" ? "bg-[#fac334] text-[#4c390c] hover:bg-[#eeb622]" : "text-[#60728a] hover:bg-[#eef3f9] hover:text-[#17468c]", className)}>{children}</button>; }
export function Avatar({ user, size = "md" }: { user?: User; size?: "sm" | "md" | "lg" | "xl" }) { return <AvatarPrimitive.Root className={cn("inline-flex shrink-0 items-center justify-center rounded-full border-2 border-white font-bold text-[#17468c]", size === "sm" ? "h-9 w-9 text-xs" : size === "lg" ? "h-13 w-13 text-sm" : size === "xl" ? "h-24 w-24 text-2xl" : "h-11 w-11 text-sm")} style={{ background: user?.avatarColor ?? "#dce8f8" }}><AvatarPrimitive.Fallback>{user?.initials ?? "MU"}</AvatarPrimitive.Fallback></AvatarPrimitive.Root>; }
export function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-sm font-semibold text-[#33445c]">{label}</span>{children}{error && <span className="mt-1 block text-xs text-red-600">{error}</span>}</label>; }
export const inputClass = "w-full min-h-11 rounded-xl border border-[#dae3ed] bg-white px-4 text-sm text-[#17263c] outline-none transition focus:border-[#17468c] focus:ring-3 focus:ring-[#17468c20] placeholder:text-[#9aa8ba]";
export function Modal({ open, onOpenChange, title, description, children, className }: { open: boolean; onOpenChange: (v: boolean) => void; title: string; description?: string; children: React.ReactNode; className?: string }) { return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-[#12243b99] backdrop-blur-[2px] data-[state=open]:animate-in" /><Dialog.Content className={cn("fixed left-1/2 top-1/2 z-50 max-h-[92vh] w-[calc(100%-24px)] max-w-xl -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-[22px] border border-[#dce5ef] bg-white p-6 shadow-2xl sm:p-8", className)}><div className="mb-6 flex items-start justify-between gap-4"><div><Dialog.Title className="text-xl font-bold tracking-tight">{title}</Dialog.Title>{description && <Dialog.Description className="mt-1 text-sm text-[#718096]">{description}</Dialog.Description>}</div><Dialog.Close className="rounded-lg p-2 text-[#7e8ca0] hover:bg-[#f1f5fa]" aria-label="Close"><X size={18}/></Dialog.Close></div>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>; }
export function EmptyState({ icon, title, description, action }: { icon: React.ReactNode; title: string; description: string; action?: React.ReactNode }) { return <div className="card flex flex-col items-center justify-center px-6 py-16 text-center"><div className="mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-[#eef4fb] text-[#17468c]">{icon}</div><h3 className="text-lg font-bold">{title}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-[#718096]">{description}</p>{action && <div className="mt-5">{action}</div>}</div>; }
export function PageHeader({ eyebrow, title, subtitle, action }: { eyebrow?: string; title: string; subtitle?: string; action?: React.ReactNode }) { return <header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div>{eyebrow && <p className="mb-2 text-xs font-bold uppercase tracking-[.16em] text-[#a5812d]">{eyebrow}</p>}<h1 className="page-title">{title}</h1>{subtitle && <p className="page-subtitle">{subtitle}</p>}</div>{action}</header>; }
export function Tag({ children, tone = "neutral" }: { children: React.ReactNode; tone?: "neutral" | "blue" | "gold" | "green" | "rose" }) { return <span className={cn("chip", tone !== "neutral" && tone)}>{children}</span>; }
export function LoadingCards({ count = 3 }: { count?: number }) { return <div className="grid gap-4">{Array.from({ length: count }, (_, i) => <div key={i} className="card p-6"><div className="flex items-center gap-3"><div className="skeleton h-11 w-11 rounded-full"/><div className="grid flex-1 gap-2"><div className="skeleton h-3 w-1/3"/><div className="skeleton h-3 w-1/5"/></div></div><div className="skeleton mt-6 h-5 w-3/4"/><div className="skeleton mt-3 h-3 w-full"/><div className="skeleton mt-2 h-3 w-4/5"/></div>)}</div>; }
